### ISSUE TITLE
3D Tiles 1.0 to 1.1 checklist

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/3d-tiles#651]
Checklist as we update 3D Tiles 1.0 to 3D Tiles 1.1. Most of these changes will go into the [draft-1.1](https://github.com/CesiumGS/3d-tiles/tree/draft-1.1) branch.

### Prerequisites

* [x] Finish https://github.com/CesiumGS/3d-tiles/pull/630
* [x] Finish https://github.com/CesiumGS/glTF/pull/56
* [x] Finish https://github.com/CesiumGS/3d-tiles/pull/634

### General
* [ ] https://github.com/CesiumGS/3d-tiles/issues/631
* [x] https://github.com/CesiumGS/3d-tiles/issues/632
* [x] Fix broken links
* [x] Remove mentions of 3D Tiles Next
* [x] Refer to 1.1 sections instead of extensions wherever applicable
* [x] What is the best way to incorporate s2, gltf, implicit tiling, metadata, and multiple contents?
* [x] Use .gltf or .glb everywhere in examples

### Specification

* [x] Metadata
  * [x] Restructure `Metadata` folder: https://github.com/CesiumGS/3d-tiles/issues/632
  * [x] Add `3DTILES_metadata` concepts to the main specification. Link to `Schema` and `PropertyTable` folders in the reference implementation.
  * [x] Move implicit tiling property table definition to `Metadata/ReferenceImplementation/PropertyTable` folder
* [x] Implicit tiling
  * [x] Add `ImplicitTiling` folder and README: https://github.com/CesiumGS/3d-tiles/pull/655
  * [x] Spatial data structures - rework to explain difference between explicit and implicit tiling. Add short summary and image for implicit tiling and link to `ImplicitTiling`.
* [x] Multiple contents
  * [x] Add to `specification/README`
  * [x] Explain distinction between `content` and `contents` and rationale for having both (i.e. avoids a breaking change), and when to use one over the other (prefer `content` for single content, better for backwards compatibility)
* [x] TileFormats
  * [x] Update individual pages with a deprecation message. Point to migration guide.
  * [x] Add `glTF` folder
    * [x] Expand on intro summary in the main spec. Show how glTF can be used for heterogeneous 3D models, instanced models, and point clouds
    * [x] Include recommended glTF extensions: https://github.com/CesiumGS/3d-tiles/issues/602
    * [x] Include details about feature identification and metadata
    * [x] Include migration guide in appendix
    * [ ] Edit pass
* [x] Update schema: https://github.com/CesiumGS/3d-tiles/pull/654
  * [x] Flesh out 3D Tiles Next schema descriptions: https://github.com/CesiumGS/3d-tiles/pull/654#discussion_r822163023
  * [x] Add `deprecated` where applicable - batch table, feature table, properties
  * [x] Should `specification/Styling/schema` be moved to `specification/schema/Styling`? https://github.com/CesiumGS/3d-tiles/pull/658
* [x] File extensions and media types: [#639](https://github.com/CesiumGS/3d-tiles/issues/639)
* [x] Update version number
* [x] Update date
* [x] Update editors
* [x] Update acknowledgements
* [x] Update JSON encoding and URIs - https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#json-encoding
* [x] Update Coordinate reference system to include tileset semantics
* [x] Geometric error overview should not mandate monotonically decreasing
* [x] Clean up transforms section. Move b3dm, i3dm, pnts specific information to their respective documents.
* [x] Regenerate property reference
* [x] Remove or replace `specification.docx` and `specification.pdf`
* [ ] Styling
  * [ ] Updates for 3D Tiles Next metadata or statistics?

### Repo Cleanup
  
* [x] Update main `README`
  * [x] Add version history (include deprecations)
  * [x] New banner image: https://demos.cesium.com/ferry-building
* [x] Remove `examples` folder. Instead there should be a prominent link in the README to [3d-tiles-samples](https://github.com/CesiumGS/3d-tiles-samples).
* [ ] Extensions
  * [ ] Update README
    * [x] Remove 3D Tiles Next section
    * [ ] Borrow extension guidelines from glTF: https://github.com/KhronosGroup/glTF/tree/main/extensions.
  * [x] Normalize formatting of `3DTILES_batch_table_hierarchy` and `3DTILES_draco_point_compression`
  * [x] For each 3D Tiles Next extension add message at the top saying that it has been promoted to core in 3D Tiles 1.1
* [x] Remove `next` folder
* [x] Update reference card for 1.1 and generate new pdf
* [x] Update Code of Conduct to the latest version used in CesiumJS: https://github.com/CesiumGS/cesium/blob/main/CODE_OF_CONDUCT.md
* [x] Update or remove `CONTRIBUTING.md`
* [x] Update or remove `CREDITS.md`
* [x] Update or remove `ECOSYSTEM.md`
* [x] Update `Q-and-A.md`
* [x] Update `RESOURCES.md`
* [ ] Go through issues and see if any are relevant for 1.1
* [ ] Pending [#631](https://github.com/CesiumGS/3d-tiles/issues/631), create branch for `1.0` and tag `1.1` release

**Comment by onsummer** [comment]
Does version 1.1 accept translation contributions?

**Comment by lilleyse** [comment]
@onsummer yes, that would be a welcome contribution! You might want to wait until version 1.1 is more stable. That should happen in the next few of months.

**Comment by onsummer** [comment]
@lilleyse Looking forward, thank you

**Comment by javagl** [comment]
The points

> Fix broken links
> Remove mentions of 3D Tiles Next
> Refer to 1.1 sections instead of extensions wherever applicable

should largely be covered by https://github.com/CesiumGS/3d-tiles/pull/673.  (Of course, the links should be checked again before the final merge. I had a look at https://github.com/tcort/markdown-link-check , and ... it may be OK, but I also have some utilities for that...)

**Comment by javagl** [comment]
As a short summary/wrap-up of the points that are not "ticked" yet:

- https://github.com/CesiumGS/3d-tiles/issues/631
- Pending https://github.com/CesiumGS/3d-tiles/issues/631, create branch for 1.0 and tag 1.1 release
  - The second one is actually part of a solution for the first one: The directory structure will likely not contain differentiation between 1.0 and 1.1, but instead, there will be tags for the versions. Details are tracked in the linked issue.

---

- Update date
- Update editors
- Update acknowledgements
  - Can be done before merging into `main`

---

- Regenerate property reference
  - This depends on wetzel - how well it works with the `2020-12` JSON schema has to be checked. **NOTE**: There are some in-page links to 'Property Reference' sections that do no longer exist. Depending on the schedule for further wetzel experiments, these might (have to) be omitted before merging into `main`

---

- Borrow extension guidelines from glTF: https://github.com/KhronosGroup/glTF/tree/main/extensions.
  - Some questions about the detail (i.e. how verbatim these guidelines will be copied) have to be sorted out, as well as our structuring for extensions that _either_ work with 1.0 or 1.1 (see #631). We don't expect extensions for 1.1 to show up quickly and en masse, so this may have low priority for now.

---

- Update reference card for 1.1 and generate new pdf
  - This is still on my plate. I need to allocate a chunk of time for that, even though I _assume_ that the "3D Tiles 1.1" reference card will _largely_ be the "Next" one, with minor structure/wording changes for the "Next" -> "1.1" transition

---

- Go through issues and see if any are relevant for 1.1
  - This is still TODO (the actual _actions_ may not be clear, but maybe the goal is exactly to sort out whether some of them have to be updated or can be closed)

**Comment by elfprince13** [comment]
Would really like to get #716 addressed before 1.1

**Comment by elfprince13** [comment]
#717 as well.
